/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableRowSorter;
import model.DAO.ClienteDAO;
import model.bean.Cliente;


/**
 *
 * @author mayco
 */
public class ListarContatos extends javax.swing.JInternalFrame {

    /**
     * Creates new form ListarContatos
     */
    public ListarContatos() throws SQLException {
        initComponents();
        DefaultTableModel modelo = (DefaultTableModel) jTablecontatos.getModel();
        jTablecontatos.setRowSorter(new TableRowSorter(modelo));
        readTable();
        
    }
    private void readTable() throws SQLException{
        DefaultTableModel modelo = (DefaultTableModel) jTablecontatos.getModel();
        ClienteDAO c = new ClienteDAO();
        
        for(Cliente cli : c.read()) {
            modelo.addRow(new Object[]{
                cli.getNome(),
                cli.getTelefone(),
                cli.getCelular(),
                cli.getEmail()
            });
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
        
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTablecontatos = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        setClosable(true);
        setIconifiable(true);

        jTablecontatos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nome", "Telafone Fixo", "Telefone Celular", "Email"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Object.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTablecontatos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTablecontatosMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTablecontatos);

        jButton1.setText("Deletar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Alterar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 671, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(198, 198, 198)
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 321, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, 49, Short.MAX_VALUE)
                    .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, 45, Short.MAX_VALUE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTablecontatosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTablecontatosMouseClicked
        // TODO add your handling code here:
        
    }//GEN-LAST:event_jTablecontatosMouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        ClienteDAO cd = new ClienteDAO();
        DefaultTableModel modelo = (DefaultTableModel) jTablecontatos.getModel();
        
        int po = jTablecontatos.getSelectedRow();
        String nome = jTablecontatos.getValueAt(po, 0).toString();
        
        try {
            for(Cliente c :cd.read()){
                if(c.getNome().equals(nome))
                    try {
                        cd.delete(c);
                    } catch (SQLException ex) {
                        Logger.getLogger(ListarContatos.class.getName()).log(Level.SEVERE, null, ex);
                    }
            }
        } catch (SQLException ex) {
            Logger.getLogger(ListarContatos.class.getName()).log(Level.SEVERE, null, ex);
        }
        modelo.removeRow(po);
        limpaTabela();
        try {
            readTable();
        } catch (SQLException ex) {
            Logger.getLogger(ListarContatos.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        ClienteDAO cd = new ClienteDAO();
        atualizarcli a = new atualizarcli();
        Cliente c = new Cliente();
        DefaultTableModel modelo = (DefaultTableModel) jTablecontatos.getModel();
        
        int po = jTablecontatos.getSelectedRow();
        String nome = jTablecontatos.getValueAt(po, 0).toString();
        
        try {
            a.atualizarcli(nome);
        } catch (SQLException ex) {
            Logger.getLogger(ListarContatos.class.getName()).log(Level.SEVERE, null, ex);
        }
      
    }//GEN-LAST:event_jButton2ActionPerformed
    public void limpaTabela(){
        DefaultTableModel tblRemove = (DefaultTableModel)jTablecontatos.getModel();
        if (tblRemove.getRowCount() > 0){
            for (int i=1;i<=tblRemove.getRowCount();i++){
                tblRemove.removeRow(i);
            }            
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTablecontatos;
    // End of variables declaration//GEN-END:variables
}
